name: vpn_wireguard_stub
description: "Just stub vpn for training."
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #DI
  provider: ^6.1.5

  #Persistent
  shared_preferences: ^2.5.3

  #Network
  wireguard_flutter: ^0.1.3

  #UI
  flutter_svg: ^2.2.0
  slider_button: ^2.1.0
  lottie: ^3.3.1

  #Architecture
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  #Utils
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  flutter_gen_runner: ^5.10.0
  build_runner:

flutter:
  #For localization
  generate: true
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/anim/

flutter_gen:
  output: lib/presentation/assets_paths
  integrations:
    flutter_svg: true
    lottie: true
